config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users, only: [:index, :show]
  resources :blocks
  get 'calendar' => 'pages#calendar'
  root 'pages#welcome'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :blocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = current_user.blocks.build
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to calendar_path, notice: 'Block was successfully created.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:beginning, :ending, :category, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def welcome
		@welcome = true
	end

	def calendar
		@blocks = current_user.blocks.all
		@block = Block.new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beginning %><br>
    <%= f.datetime_select :beginning %>
  </div>
  <div class="field">
    <%= f.label :ending %><br>
    <%= f.datetime_select :ending %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing Block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Beginning</th>
      <th>End</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.beginning %></td>
        <td><%= block.ending %></td>
        <td><%= block.category %></td>
        <td><%= block.user.email %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beginning:</strong>
  <%= @block.beginning %>
</p>

<p>
  <strong>End:</strong>
  <%= @block.ending %>
</p>

<p>
  <strong>Category:</strong>
  <%= @block.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @block.user.email %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>
<%= link_to "Delete", @block, method: :delete, data: { confirm: "You sure?" } %>

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Ninja Scheduler</p>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Ninja Schedule</h1>
                        <p class=>Ninja Calendar is for those who want a simpler scheduling tool to manage time constraints of multiple user calendars on different systems.</p>
                        <%= audio_tag "chop.wav", class: "audio-play" %>
                        <a href="#about" class="audio-play btn btn-circle page-scroll"></a>
                    </div>
                </div>
            </div>
        </div>
    </header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <%= link_to root_path, class:"navbar-brand" do %>
                  <span class="light"><i class="fa fa-cogs"></i>Ninja</span> Schedule
                <% end %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <% if user_signed_in? %>
                        <li><%= link_to "Group Calendar", calendar_path %></li>
                        <li><%= link_to "New Meeting" %></li>
                      
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to "Profile", current_user %></li>
                          <li class="divider"></li>
                          <li class="dropdown-header">Callin' it quits?</li>
                          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                        </ul>
                      </li>
                    <% else %>
                      <li><%= link_to "Sign Up", new_user_registration_path %></li>
                      <li><%= link_to "Sign In", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninja</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body  id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

	<%= render 'layouts/navbar' %>
	<% if @welcome %>
		<%= render 'layouts/header' %>
	<% end %>
		<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>
		<%= yield %>


	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/calendar.html.erb
<div id='calendar'></div>

<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <h4>How long do you want to meet for?</h4>
    <%= number_field_tag :something %>
  </div>
  <div>
  <div class="field">
    <%= f.label :beginning %><br>
    <%= f.datetime_select :beginning %>
  </div>
  <div class="field">
    <%= f.label :ending %><br>
    <%= f.datetime_select :ending %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>




<div class="container">
<%= render partial: "shared/block", collection: @blocks %>

</div>

app/views/pages/welcome.html.erb
    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Ninja Schedule</h2>
                <p>Visit the <a href="https://ninjacalendar.wordpress.com/">Ninja Schedule </a> page to learn more about its features.</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Become a scheduling ninja!</h2>
                    <p>It's easy, click this button below and become a master.</p>
                    <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact the Ninja Sensei!</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p><a href="mailto:feedback@startbootstrap.com">feedback@thescheduleninja.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

app/views/shared/_block.html.erb
<%= block.category %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>